{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/blueprints/blog/views.py
from flask import Blueprint, render_template, abort

from .models import Post, Category, Tag

blog = Blueprint(
    'blog', __name__, template_folder='templates', url_prefix='/blog')


def custom_list_view(key):
    import os
    cd = os.path.dirname(os.path.abspath(__file__))
    lists_dir = os.path.join(cd, 'templates/blog/lists')

    result = None
    for (root, dir_names, file_names) in os.walk(lists_dir):
        for file_name in file_names:
            if key in file_name:
                result = file_name
                break
        if result:
            break

    if result:
        return 'blog/lists/' + file_name
    else:
        return 'blog/result_list.jinja2'


#    Blog Index -------------------------------------------------------------------------


@blog.route('/')
def index():
    """Display the ten most-recent posts."""

    categories = Category.query.all()
    posts = Post.query.filter_by(is_published=True) \
                    .order_by(Post.created_on.desc()).limit(10)
    return render_template(
        'blog/index.jinja2', categories=categories, posts=posts)


#    Post Details -----------------------------------------------------------------------


@blog.route('/<category_slug>/<post_slug>/')
def post_detail(category_slug, post_slug):
    """Display a single post.

    Args:
        category_slug (str): not required logically, but used for sanity checking.
        post_slug (str): key to search for post.
    """

    result = None

    posts = Post.query.all()
    for post in posts:
        if post.slug == post_slug:
            result = post
            break

    if not result:
        abort(404)

    # Although this _shouldn't_ do anything, it's here for my sanity. :)
    if result.category.slug != category_slug:
        abort(404)

    return render_template('blog/post_detail.jinja2', post=result)


#    Search Results ---------------------------------------------------------------------


@blog.route('/<slug>/')
def category_detail(slug):
    result = None

    categories = Category.query.all()
    for category in categories:
        if category.slug == slug:
            result = category
            break

    if not result:
        abort(404)

    template_file = custom_list_view(key=slug)
    return render_template(template_file, result=result)


@blog.route('/tag/<slug>/')
def tag_detail(slug):
    result = None

    tags = Tag.query.all()
    for tag in tags:
        if tag.slug == slug:
            result = tag
            break

    if not result:
        abort(404)

    template_file = custom_list_view(key=slug)
    return render_template(template_file, result=result)

{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/blueprints/page/views.py
from flask import Blueprint, render_template, make_response

from lib.urls import all_urls

page = Blueprint('pages', __name__, template_folder='templates')


@page.route('/')
def index():
    return render_template('page/index.jinja2')


@page.route('/policy/terms/')
def terms():
    return render_template('page/terms.jinja2')


@page.route('/policy/privacy/')
def privacy():
    return render_template('page/privacy.jinja2')


@page.route('/sitemap.xml')
def sitemap():
    template = render_template('page/sitemap.jinja2', urls=all_urls())
    response = make_response(template)
    response.headers['Content-Type'] = 'application/xml'

    return response


#@page.route('/google36c6d388c4053b8a.html')
#def google_webmaster():
#    return render_template('page/google_webmaster.jinja2')

{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/templates/layouts/modules/analytics.jinja2
{% if config['ANALYTICS_CLICKY_ID'] %}
    <script type="text/javascript">
    var clicky_site_ids = clicky_site_ids || [];
    clicky_site_ids.push({{ config['ANALYTICS_CLICKY_ID'] }});
    (function() {
        var s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = '//static.getclicky.com/js';
        ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
    })();
    </script>
    <noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/{{ config['ANALYTICS_CLICKY_ID'] }}ns.gif" /></p></noscript>
{% endif %}

{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/templates/layouts/modules/banner_image.jinja2
{% if banner_title and banner_img %}
    <header class="banner" style="background:linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.5)),url({{ banner_img }});background-size:cover;">
        <div class="title">
            <h1>{{ banner_title }}</h1>
        </div>
    </header>
{% endif %}

{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/templates/layouts/modules/comments.jinja2
<hr/>

<div class="fb-comments" data-href="{{ canonical_request_url() }}"></div>

{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/templates/layouts/modules/css.jinja2
{% if config['DEBUG'] %}
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/vendor/bootstrap.css') }}">

    <!-- App overrides -->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">

    <!-- Vendor applications -->
    <link rel="stylesheet" href="{{ url_for('static', filename='fontello/fontello.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/vendor/highlight-solarized-light.css') }}">
{% else %}
    <link rel="stylesheet" href="/static/styles/main.css">
{% endif %}

{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/templates/layouts/modules/favicon.jinja2
{% if config['DEBUG'] %}
    <link rel="icon" href="/static/images/favicon_debug.ico" sizes="16x16">
{% else %}
    <link rel="icon" href="/static/images/favicon.ico" sizes="16x16">
{% endif %}

{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/templates/layouts/modules/footer.jinja2
<footer class="footer">
    <div class="container">
        {% if config['GITHUB_URL'] %}
            <ul class="list-inline" id="footer-right">
                <li>Made with <a href="{{ config['GITHUB_URL'] }}" target="_blank">&hearts;</a> in <a href="http://www.cityofallegan.org/" target="_blank">Allegan</a>, <a href="http://www.michigan.org/" target="_blank">Michigan</a>.</li>
            </ul>
        {% endif %}

        <ul class="list-inline">
            <li class="text-muted">Michael Hoyt &copy; {{ current_year() }}</li>
            <li><a href="{{ url_for('pages.privacy') }}">Privacy Policy</a></li>
            <li><a href="{{ url_for('pages.terms') }}">Terms of Service</a></li>
            <li><a href="{{ url_for('pages.sitemap') }}">Sitemap</a></li>
        </ul>
    </div>
</footer>

{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/templates/layouts/modules/header.jinja2
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Hoyt.IO</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('pages.index') }}">Home</a></li>
                <li><a href="{{ url_for('blog.index') }}">Blog</a></li>
                <!-- Dropdown
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
                -->
            </ul>
            <!-- Right aligned menu items
            <ul class="nav navbar-nav navbar-right">
                <li><a href="../navbar/">Default</a></li>
                <li><a href="../navbar-static-top/">Static top</a></li>
                <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
            </ul>
            -->
        </div><!--/.nav-collapse -->
    </div>
</nav>

{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/templates/layouts/modules/metadata.jinja2
{% set page = page_attributes(request.path) %}

{% macro open_graph() -%}
    {% set og_set = ['audio', 'determiner', 'video'] %}
    {% set og_enabled = True %}

    {% set og_title = page.title %}
    {% if page.og_title %}
        {% set og_title = page.og_title %}
    {% endif %}

    {% if (not og_title) or (not page.og_image) %}
        {% set og_enabled = False %}
    {% endif %}

    {% if og_enabled %}
        {% for tag in og_set %}
            {% if page['og_' + tag] %}
                <meta property="og:{{ tag }}" content="{{ page['og_' + tag] }}" />
            {% endif %}
        {% endfor %}

        <meta property="og:image" content={{ canonical_url_for('static', filename=page.og_image) }} />
        <meta property="og:url" content="{{ canonical_request_url() }}" />
        <meta property="og:site_name" content="Hoyt.IO" />

        {% if page.meta_description %}
            <meta property="og:description" content="{{ page.meta_description }}" />
        {% endif %}

        {% set og_type = 'website' %}
        {% if page['og_type'] %}{% set og_type = page['og_type'] %}{% endif %}
        <meta property="og:type" content="{{ og_type }}" />

        <!-- TODO: Specials for each type: http://ogp.me/#types -->
    {% endif %}
{%- endmacro %}

{{cookiecutter.project_name}}/{{cookiecutter.app_name}}/templates/layouts/modules/scripts.jinja2
<script src="{{ url_for('static', filename='scripts/vendor/highlight.js') }}"></script>
<script>hljs.initHighlightingOnLoad();</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>